<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('car_videos', function (Blueprint $table) {
            $table->id();
            $table->foreignId('car_id')->constrained()->onDelete('cascade');
            $table->foreignId('company_id')->constrained()->onDelete('cascade');
            $table->string('video_url'); // YouTube, Vimeo, or direct URL
            $table->enum('platform', ['youtube', 'vimeo', 'direct_url'])->default('youtube');
            $table->string('video_title');
            $table->text('video_description')->nullable();
            $table->enum('category', ['exterior', 'interior', 'engine', 'test_drive', 'overview', 'other'])->default('overview');
            $table->integer('duration')->nullable(); // in seconds
            $table->string('thumbnail_url')->nullable(); // auto-generated by platform
            $table->boolean('is_featured')->default(false);
            $table->integer('sort_order')->default(0);
            $table->json('metadata')->nullable(); // extra info like video ID, embed code, etc.
            $table->timestamps();
            
            // Indexes
            $table->index(['car_id', 'sort_order']);
            $table->index(['company_id', 'platform']);
            $table->index('is_featured');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('car_videos');
    }
};
